site_name: HBCD DCC Docs

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - toc:
      permalink: '🔗'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/extra.js
  - https://www.googletagmanager.com/gtag/js?id=G-95CHYYTVHC
  - js/ga.js

extra:
  analytics:
    provider: google
    property: G-95CHYYTVHC

extra_css:
  - css/alerts.css
  - css/custom.css
  - css/collapsible.css
  - css/copybox.css
  - css/banners.css
  - css/hide-sidebar.css
  - css/hoverable_elements.css
  - css/legends.css
  - css/logos.css
  - css/mermaid.css
  - css/notifications.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
  - css/reduce-righthand-whitespace.css
  - css/warnings.css
  - css/qc-wf-banners.css

plugins:
  - search
  - mermaid2:
      arguments:
        startOnLoad: true
        flowchart:
          htmlLabels: true
        theme: base  # "default" or "base" 
        themeVariables:
          primaryColor: "#ffffff"
          primaryTextColor: "#000000"
          tertiaryColor: "#f0f0f0"
        layout: elk
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - Overview: index.md
  - Workflows & SOPs:
    - HDCC Structure: orgcharts.md
    - Quality Control Procedures: workflows/qc.md
    - Data Processing Workflows: workflows/data-proc-wf.md
    - Release SOP: workflows/release-wf.md
  - Standards & Conventions:
    - Variable Naming: standards/naming-conventions.md
  - Beta Release Notes: 
   # - 🚧 Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Beta Release 15.1: changelog/versions/BR15.1.md
        - Beta Release 15.0: changelog/versions/BR15.md
        - Beta Release 14.8: changelog/versions/BR14.8.md 
        - Beta Release 14.7: changelog/versions/BR14.7.md 
        - Beta Release 14.6: changelog/versions/BR14.6.md   
        - Beta Release 14.5: changelog/versions/BR14.5.md  
        - Beta Release 14.0: changelog/versions/BR14.md    
        - Beta Release 13.0: changelog/versions/BR13.md
        - Beta Release 12.0: changelog/versions/BR12.md
        - Beta Release 11.0: changelog/versions/BR11.md
        - Beta Release 10.0: changelog/versions/BR10.md
        - Beta Release 9.0: changelog/versions/BR9.md
        - Beta Release 8.0: changelog/versions/BR8.md
        - Beta Release 7.5: changelog/versions/BR7.5.md
        - Beta Release 7.0: changelog/versions/BR7.md      
        - Beta Release 6.5: changelog/versions/BR6.5.md    
        - Beta Release 6.0: changelog/versions/BR6.md          
        - Beta Release 5.0: changelog/versions/v1.4.md
        - Beta Release 4.0: changelog/versions/v1.3.md
        - Beta Release 3.0: changelog/versions/v1.2.md
        - Beta Release 2.0: changelog/versions/v1.1.md
        - Beta Release 1.0: changelog/versions/v1.0.md
  - Workgroup Instructions:
      - Access BR Data: internal/br-review.md
      - Report Issues: internal/reportissues.md
      - Request Updates to Documentation: internal/docs-updates.md
  - RESOURCES: resources.md    