site_name: HBCD DCC Docs

use_directory_urls: true

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - toc:
      permalink: '🔗'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/extra.js
  - https://www.googletagmanager.com/gtag/js?id=G-95CHYYTVHC
  - js/ga.js

extra:
  analytics:
    provider: google
    property: G-95CHYYTVHC

extra_css:
  - css/alerts.css
  - css/custom.css
  - css/collapsible.css
  - css/copybox.css
  - css/banners.css
  - css/hide-sidebar.css
  - css/hoverable_elements.css
  - css/legends.css
  - css/logos.css
  - css/mermaid.css
  - css/notifications.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
  - css/reduce-righthand-whitespace.css
  - css/warnings.css
  - css/qc-wf-banners.css

plugins:
  - search
  - mermaid2:
      arguments:
        startOnLoad: true
        flowchart:
          htmlLabels: true
        theme: base  # "default" or "base" 
        themeVariables:
          primaryColor: "#ffffff"
          primaryTextColor: "#000000"
          tertiaryColor: "#f0f0f0"
        layout: elk
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - Overview: index.md
  