site_name: Internal HBCD Data Release Docs

theme:
  name: readthedocs
  custom_dir: docs/overrides # for template overrides, used in this case for addition of "Page Last Updated: <DATE>" to pages
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - toc:
      permalink: '🔗'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/extra.js

extra_css:
  - css/custom.css
  - css/copybox.css
  - css/banners.css
  - css/hoverable_elements.css
  - css/legends.css
  - css/mermaid.css
  - css/headers.css
  - css/tables.css
  - overrides/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css

plugins:
  - search
  - mermaid2:
      arguments:
        startOnLoad: true
        flowchart:
          htmlLabels: true
        theme: default  # or "base" 
        themeVariables:
          primaryColor: "#ffffff"
          primaryTextColor: "#000000"
          tertiaryColor: "#f0f0f0"
        layout: elk
  - git-revision-date-localized:
      type: date

docs_dir: docs

nav: 
  - ABOUT: index.md
  - Report Issues: internal/reportissues.md
  - Review Beta Data Release Site: internal/beta_release_site_review.md
  - Workflows:
    - S3 Buckets: workflows/s3.md
  - CHANGE LOG: 
    - Pending & Upcoming Updates: changelog/pending.md
    - Known Issues: changelog/knownissues.md
    - Version History:    
        - Beta Release 15: changelog/versions/BR15.md
        - Beta Release 14.8: changelog/versions/BR14.8.md 
        - Beta Release 14.7: changelog/versions/BR14.7.md 
        - Beta Release 14.6: changelog/versions/BR14.6.md   
        - Beta Release 14.5: changelog/versions/BR14.5.md  
        - Beta Release 14: changelog/versions/BR14.md    
        - Beta Release 13: changelog/versions/BR13.md
        - Beta Release 12: changelog/versions/BR12.md
        - Beta Release 11: changelog/versions/BR11.md
        - Beta Release 10: changelog/versions/BR10.md
        - Beta Release 9: changelog/versions/BR9.md
        - Beta Release 8: changelog/versions/BR8.md
        - Beta Release 7.5: changelog/versions/BR7.5.md
        - Beta Release 7: changelog/versions/BR7.md      
        - Beta Release 6.5: changelog/versions/BR6.5.md    
        - Beta Release 6: changelog/versions/BR6.md          
        - Beta Release 5: changelog/versions/v1.4.md
        - Beta Release 4: changelog/versions/v1.3.md
        - Beta Release 3: changelog/versions/v1.2.md
        - Beta Release 2: changelog/versions/v1.1.md
        - Beta Release 1: changelog/versions/v1.0.md
  - Resources:
    - Slides: slides.md
    - Org Charts: orgcharts.md