---
config:
  layout: elk
  look: neo
  theme: redux
---
flowchart LR
 subgraph Capture_LORIS["<b>Sites Capture</b><br>"]
        n13@{ label: "REDCap (<a href=\"../../orgcharts/#j-craig-venter-institute\" rel=\"noopener\" target=\"_blank\">JCVI</a>)" }
        n14@{ label: "TLFB (<a href=\"../../orgcharts/#j-craig-venter-institute\" rel=\"noopener\" target=\"_blank\">JCVI</a>)" }
        n16@{ label: "<a href=\"../../orgcharts/#ripple\" rel=\"noopener\" target=\"_blank\">Ripple</a>" }
        n17@{ label: "<a href=\"../data-proc-wf/#third-party\" target=\"_top\">Third Party</a>" }
        n18["Biospecimens"]
        n19["Genetics"]
  end
 subgraph s1["Processing<br><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener target=_blank>UMN MSI</a>"]
        n15@{ label: "<b>S3</b><br><a href=\"../../orgcharts/#loris\" rel=\"noopener\" target=\"_blank\">LORIS</a><br>Production<br>" }
  end
 subgraph s2["Capture<br><a href=../../orgcharts/#health-sciences-technology rel=noopener target=_blank>UMN HST</a>"]
        n20@{ label: "<a href=\"https://sampled.com/\" rel=\"noopener\" target=\"_blank\">Sampled</a>" }
        n21["UMN SCE"]
        n22@{ label: "<a href=\"https://www.usdtl.com/\" rel=\"noopener\" target=\"_blank\">USDTL</a>" }
  end
 subgraph s3["Non-Production"]
        n23@{ label: "<a href=\"../../orgcharts/#loris\" rel=\"noopener\" target=\"_blank\">LORIS</a><br>Sandbox" }
  end
 subgraph s4["Release Staging<br><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener target=_blank>UMN MSI</a>"]
        n25@{ label: "<div style=\"color:\"><span style=\"background-color:\"><b>S3</b></span></div><div style=\"color:\"><span style=\"background-color:\"><font style=\"\"><b>Lasso<br>Staging</b></font></span></div>" }
        n26["<b>S3<br></b>Lasso<br>Prerelease<br>"]
  end
 subgraph s5["De-Identification"]
        n28["Untitled Node"]
  end
    n13 --> n15
    n14 --> n15
    n16 --> n21
    n17 --> n21
    n19 --> n20
    n18 --> n22
    n20 --> n21
    n22 --> n21
    n21 --> n15 & n23
    n25 -- <br> --> n26
    n26 --> n27@{ label: "<a href=\"../../orgcharts/#lasso\" rel=\"noopener\" target=\"_blank\"><b>LASSO</b></a><br><b>INGESTION</b>" }
    n15 --> n25
    n13@{ shape: lean-r}
    n14@{ shape: lean-r}
    n16@{ shape: lean-r}
    n17@{ shape: lean-r}
    n18@{ shape: lean-r}
    n19@{ shape: lean-r}
    n15@{ shape: disk}
    n20@{ shape: disk}
    n21@{ shape: disk}
    n22@{ shape: disk}
    n23@{ shape: disk}
    n25@{ shape: disk}
    n26@{ shape: disk}
    n27@{ shape: circle}
    style n13 fill:#FFD600
    style n14 fill:#FFD600
    style n16 fill:#FFD600
    style n17 fill:#FFD600
    style n18 fill:#FFD600
    style n19 fill:#FFD600
    style n15 fill:#C8E6C9
    style n20 fill:#C8E6C9
    style n21 fill:#C8E6C9
    style n22 fill:#C8E6C9
    style n23 fill:#C8E6C9
    style n25 fill:#C8E6C9
    style n26 fill:#C8E6C9
    style n27 fill:#FFD600
    style Capture_LORIS fill:#FFF9C4
    style s1 fill:#E1BEE7
    style s2 fill:#BBDEFB
    style s3 fill:#BBDEFB
    style s4 fill:#E1BEE7
