---
config:
  layout: elk
---
flowchart TB
    CDNI["<b>Damien Fair</b> HDCC Co-Director"] --- n2(["<b>MRI Acquisition</b>"]) & n3(["<b>Processed MRI QC</b>"]) & n7(["<b>Pipeline Standardization</b>"]) & n10(["<b>HDCC Release Docs</b>"])
    n2 --- n4["<b>Kimberly Weldon, PhD</b><br>MR Specialist (Siemens)"]
    n3 --- n5@{ label: "<b>Eric Feczko, PhD</b><br>QC Lead &amp; Neuroinformatics<br>----------------<br><span style=\"--tw-scale-x:\"><b>Michael Anderson, PhD</b><br></span>QC Analyst" } & n9["<b>Lucille A. Moore, PhD</b><br>Release Docs Lead &amp; Neuroinformatics"]
    n7 --- n9
    n10 --- n9
    n11["<b>Damien Fair, PA-C, PhD</b><br>HDCC Co-Director"] --> n2
    CDNI@{ shape: anchor}
    n5@{ shape: rect}
    n11@{ shape: rect}
    style CDNI fill:#BBDEFB,stroke:#2962FF
    style n2 fill:#E1BEE7,stroke:#AA00FF
    style n3 fill:#E1BEE7,stroke:#AA00FF
    style n7 fill:#E1BEE7,stroke:#AA00FF
    style n10 fill:#E1BEE7,stroke:#AA00FF
    style n4 fill:#BBDEFB,stroke:#2962FF
    style n5 fill:#BBDEFB,stroke:#2962FF
    style n9 fill:#BBDEFB,stroke:#2962FF
    style n11 fill:#BBDEFB,stroke:#2962FF,stroke-width:4px,stroke-dasharray: 0
    linkStyle 9 stroke:none,fill:none
