---
config:
  layout: elk
---
flowchart TB
    n13["HDCC Co-Director"]
    n14["Team member(s)"]
    n15["Program Manager/Study Officer"]
    n16["Organization"]
    n17(["Team within an org"])
    n14@{ shape: rect}
    n15@{ shape: rect}
    n16@{ shape: rect}
    style n13 stroke:#2962FF,fill:#BBDEFB,stroke-width:4px,stroke-dasharray: 0
    style n14 stroke:#2962FF,fill:#BBDEFB
    style n15 fill:#C8E6C9,stroke:#00C853,stroke-width:2px,stroke-dasharray: 0
    style n16 stroke:#AA00FF,fill:#E1BEE7
    style n17 stroke:#AA00FF,fill:#E1BEE7
