---
config:
  layout: elk
---
flowchart TB
    L["<b>Maren Macgregor-Hannah</b><br>HDCC Program Manager"] --- N(["<b>Advanced System Operations</b>"]) & O(["<b>Informatics &amp; Processing</b>"]) & P(["<b>Data Steward</b>"]) & n8(["<b>Security &amp; Compliance</b>"])
    N --- Q["<b>Jesse Erdmann</b><br>Senior SysOps
    ----------
    <b>Kimberleigh Breen</b><br>Data Manager
    ----------
    <b>Sriharshitha Anuganti<br>Alyssa Oksa<br>Anders Skaar</b><br>DevOps"]
    O --- n4["<b>Timothy Hendrickson</b><br>Neuroimaging Lead
    ----------
    <b>Erik Lee</b><br>Pipeline Lead
    ----------
    <b>Monalisa Biles</b><br>Analyst"]
    P --- n7["<b>Jeff Shi</b><br>Informatics Consultant
    ----------
    <b>Borgne Raasch</b><br>Data Steward"]
    n8 --- n9["<b>Naomi Hospodarsky-Sutherland</b>"]
    n10["<b>Thomas Pengo, PhD</b><br>Co-Director, Informatics"]
    n11["<b>Maren Macgregor-Hannah</b><br>HDCC Program Manager"]
    L@{ shape: anchor}
    n11@{ shape: rect}
    style L fill:#C8E6C9,stroke:#00C853
    style N fill:#E1BEE7,stroke:#AA00FF
    style O fill:#E1BEE7,stroke:#AA00FF
    style P fill:#E1BEE7,stroke:#AA00FF
    style n8 fill:#E1BEE7,stroke:#AA00FF
    style Q fill:#BBDEFB,stroke:#2962FF
    style n4 fill:#BBDEFB,stroke:#2962FF
    style n7 fill:#BBDEFB,stroke:#2962FF
    style n9 fill:#BBDEFB,stroke:#2962FF
    style n10 fill:#BBDEFB,stroke:#2962FF
    style n11 fill:#C8E6C9,stroke:#00C853
