---
config:
  layout: elk
---
flowchart TB
    n16["<b>Nathan Fox, PhD</b><br>Associate Dir, EEG Data Core"] --- n17(["<b>Preprocessing</b>"]) & n19(["<b>Coding &amp; QC</b>"]) & n29(["<b>Site Supervision</b>"])
    n17 --- n18["<b>Whitney Kasenetz</b><br>Preprocessing Liaison"]
    n19 --- n27["<b>Kira Ashton</b><br>Coding &amp; QC"] & n28["<b>Dylan Gilbreath</b><br>Pipeline Developer"] & n30["<b>Trisha Maheswari</b><br>Site Supervisor<br><b>Elise Harris</b><br>Site Oversight"]
    n29 --- n30
    n32["<b>Nathan Fox, PhD</b><br>Associate Dir, EEG Data Core"]
    n33["<b>Santiago Morales</b><br>Co-I &amp; Coding Lead"]
    n16@{ shape: anchor}
    n32@{ shape: rect}
    n33@{ shape: rect}
    style n16 fill:#BBDEFB,stroke:#2962FF
    style n17 fill:#E1BEE7,stroke:#AA00FF
    style n19 fill:#E1BEE7,stroke:#AA00FF
    style n29 fill:#E1BEE7,stroke:#AA00FF
    style n18 fill:#BBDEFB,stroke:#2962FF
    style n27 fill:#BBDEFB,stroke:#2962FF
    style n28 fill:#BBDEFB,stroke:#2962FF
    style n30 fill:#BBDEFB,stroke:#2962FF
    style n32 fill:#BBDEFB,stroke:#2962FF
    style n33 fill:#C8E6C9,stroke:#00C853
