---
config:
  layout: elk
---
flowchart TB
    n5["tuitle"] --- C@{ label: "<a href=\"../orgcharts#center-for-developmental-neuroimaging\" target=\"_top\"><b>Center for Developmental NeuroImaging</b></a>" } & E@{ label: "<a href=\"../orgcharts#midb-informatics-hub-msi\" target=\"_top\"><b>MIDB Informatics Hub &amp; MSI</b></a>" } & D@{ label: "<a href=\"../orgcharts#midb-analytics-hub\" target=\"_top\"><b>MIDB Analytics Hub</b></a>" } & B@{ label: "<a href=\"../orgcharts#health-sciences-technology\" target=\"_top\"><b>Health Sciences Technology</b></a>" }
    n3>"<b><br>UMN LEADS &gt;<br><br></b>"] === n5
    A["<b>Damien Fair, PA-C, PhD</b><br>HDCC Co-Director"]
    A1["<b>Reed McEwan, MS</b><br>Sr Research Developer"]
    n1["<b>Maren Macgregor-Hannah<br></b>Program Manager"]
    n5@{ shape: anchor}
    style C fill:#E1BEE7,stroke:#AA00FF
    style E fill:#E1BEE7,stroke:#AA00FF
    style D fill:#E1BEE7,stroke:#AA00FF
    style B fill:#E1BEE7,stroke:#AA00FF
    style n3 fill:transparent,stroke:none,stroke-width:4px
    style A fill:#BBDEFB,stroke:#2962FF,stroke-width:4px
    style A1 fill:#BBDEFB,stroke:#2962FF
    style n1 fill:#C8E6C9,stroke:#00C853
    click C "#center-for-developmental-neuroimaging"
    click E "#midb-informatics-hub-msi"
    click D "#midb-analytics-hub"
    click B "#health-sciences-technology"
