---
config:
  layout: elk
  look: neo
  theme: redux
---
flowchart LR
 subgraph s2["<b>Pipeline Processing of Raw BIDS Data via CBRAIN</b><br><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener>UMN MSI</a>"]
        n25["<i>S3:<br>De-ID /<br>Derivatives</i>"]
  end
 subgraph s3["<b>Derivatives &amp; BrainSwipes QC Data Re-Identified for LORIS<br></b><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener>UMN MSI</a>"]
        n28["<i>S3:<br>Main PR / Derivatives</i>"]
        n46["<i>S3:<br>Main PR / BrainSwipes</i>"]
  end
 subgraph s4["<b>Perform BrainSwipes QC of MRI Derivatives<br></b><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener>UMN MSI</a><br><a href=../data-proc-wf/#brainswipes><i>Click for Details</i></a>"]
        n33["<i>S3:<br>De-ID / BrainSwipes</i>"]
  end
 subgraph s5["<b>Release Data Copied to Lasso Staging Environment</b><br><a href=../../orgcharts/#midb-informatics-hub-msi>UMN MSI</a><br><a href=../data-proc-wf/#copy-to-release target=_top><i>Click for Details</i></a>"]
        n36["<i>S3: Lasso PR</i>"]
  end
 subgraph s7["<br>"]
        n40(("<b>LASSO<br>INGESTION</b>"))
  end
 subgraph s8["<b>Re-ID Derivatives Copied to Lasso HDCC for<br>Ongoing QC</b><br><a href=../data-proc-wf/#lasso-hdcc-qc-environment><i>Click for Details</i></a>"]
        n48["<i>S3: QC Env</i>"]
  end
 subgraph s9["<b>Raw BIDS De-Identified Before CBRAIN Processing</b><br><a href=../../orgcharts/#midb-informatics-hub-msi rel=noopener>UMN MSI</a>"]
        n50["<i>S3:<br>De-ID / BIDS</i>"]
  end
    n25 --> n28 & n36 & n33
    n28 --> n48
    n36 --> n40
    n33 --> n46
    n50 --> n25
    n51["<i><b>S3:<br>Main PR / BIDS</b><br></i>"] --> n50
    n52@{ label: "<i style=\"--tw-scale-x:\">S3: De-ID-List</i>" } --> n50
    n25@{ shape: disk}
    n28@{ shape: disk}
    n46@{ shape: disk}
    n33@{ shape: disk}
    n36@{ shape: disk}
    n48@{ shape: disk}
    n50@{ shape: disk}
    n51@{ shape: disk}
    n52@{ shape: disk}
    style n25 fill:#E1BEE7
    style n28 fill:#BBDEFB
    style n46 fill:#BBDEFB
    style n33 fill:#FFD600,color:#000000
    style n36 fill:#C8E6C9
    style n40 fill:#C8E6C9,stroke:#00C853,stroke-width:4px,stroke-dasharray: 0
    style n48 fill:#FFCDD2,stroke:#000000
    style n50 fill:#FFE0B2
    style n51 fill:#BBDEFB
    style n52 fill:#BBDEFB
    style s4 fill:#FFF9C4
    style s5 fill:#EBFFEB
    style s2 fill:#FAD9FF
    style s3 fill:#E3F2FD
    style s7 stroke:none,fill:transparent
    style s8 fill:#ffe9eb
    style s9 fill:#fbebd3
